name: Assignment on module-3 on CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Application
    runs-on: self-hosted  # Run the test job on self hosted: 'self-hosted', 'Windows', 'X64'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Action for checkout repository code

     #   - name: Setup Node.js
     #     uses: actions/setup-node@v3
     #     with:
     #       node-version: '20'  # Node.js version 20

     #   - name: Install dependencies
     #     run: npm install      # Install Node.js dependencies
     
     - name: Run tests and capture results
        # The 'test' script in package.json will create 'test-results.txt'
       run: npm test

      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results # Name of the artifact
          path: test-results.txt # Path to the file to upload

     #   - name: Run tests and capture results
     #     run: |
      #      mkdir -p test-results
      #      npm test > test-results/results.txt # Remove '|| true' to fail on test failure

      #  - name: Upload test results
      #    uses: actions/upload-artifact@v3
     #     with:
      #      name: test-results
      #      path: test-results/results.txt

  deploy:
    name: Deploy to Self-Hosted Runner
    needs: test # This job depends on the 'test' job succeeding
    runs-on: self-hosted # self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # download test results 
     #    - name: Download test results
     #      uses: actions/download-artifact@v3
      #     with:
      #       name: test-results

      # show test results 
       #  - name: Show test results
        #   run: cat test-results/results.txt

       # - name: Install production dependencies
       #   run: npm install --omit=dev # Install only production dependencies


       # - name: Stop previous application
       #   run: pm2 delete app || true

       # - name: Start application with pm2
       #   run: pm2 start index.js --name app
